config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :games do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:create]

  end

  resources :bookings, only: [:destroy] do
    resources :reviews, only: [:create]
  end

  resource :dashboard, only: [:show]
  resources :favorites, only: [:index, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  has_many :games


  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
	after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :city, :city_code, :street_number, :street, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :city, :city_code, :street_number, :street, :photo])
  end

  private
	
	def skip_pundit? #=> si on est dans un controller de device, on ne met pas un pundit / si on est sur le controller de pages
		devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @games = Game.where(user: current_user)
    authorize @games
    # @bookings = Booking.where(user: current_user)

    # @review = Review.new

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: :new

  def index
    @games = policy_scope(Game)
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
  end

  def new
    @game = Game.new
    authorize @game
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    authorize @game
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
    authorize @game
  end

  def update
    @game = Game.find(params[:id])
    authorize @game
    @game.update(game_params)

    redirect_to game_path(@game)

  end

  def destroy
    @game = Game.find(params[:id])
    authorize @game
    @game.destroy

    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :price, :description, :category, :condition, :min_age, :max_age, :min_players, :max_players, :time, :content)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.input :name, placeholder: "Game's name" %>
  <%= f.input :description, placeholder: "Explain what this game is about"  %>
  <%= f.input :price, as: :numeric, placeholder: "Price per day"  %>
  <%= f.input :category, prompt: "Select", collection:  ["Escape game", "Cooperative board game", "Strategy game", "Party game", "Card game", "Classic board game", "General culture games"] %>
  <%= f.input :condition, prompt: "Select", collection: ["very good state", "good state", "satisfactory"] %>
  <%= f.input :min_age, as: :numeric, placeholder: "3" %>
  <%= f.input :max_age, as: :numeric, placeholder: "99"  %>
  <%= f.input :min_players, as: :numeric, placeholder: "4"  %>
  <%= f.input :max_players, as: :numeric, placeholder: "12" %>
  <%= f.input :time, placeholder: "45 min" %>
  <%= f.input :content, placeholder: "25 cards, 1 board, 5 pawns" %>
  <%= f.submit %>
<% end %>

app/views/games/index.html.erb
<% @games.each do |game| %>
<%= game.name %>
<% end %>

app/views/games/new.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.input :name, placeholder: "Game's name" %>
  <%= f.input :description, placeholder: "Explain what this game is about"  %>
  <%= f.input :price, as: :numeric, placeholder: "Price per day"  %>
  <%= f.input :category, prompt: "Select", collection:  ["Escape game", "Cooperative board game", "Strategy game", "Party game", "Card game", "Classic board game", "General culture games"] %>
  <%= f.input :condition, prompt: "Select", collection: ["very good state", "good state", "satisfactory"] %>
  <%= f.input :min_age, as: :numeric, placeholder: "3" %>
  <%= f.input :max_age, as: :numeric, placeholder: "99"  %>
  <%= f.input :min_players, as: :numeric, placeholder: "4"  %>
  <%= f.input :max_players, as: :numeric, placeholder: "12" %>
  <%= f.input :time, placeholder: "45 min" %>
  <%= f.input :content, placeholder: "25 cards, 1 board, 5 pawns" %>
  <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<%= @game.name %>
<%= @game.description %>
<%= @game.price %>
<%= @game.category %>
<%= @game.condition %>
<%= @game.min_age %>
<%= @game.max_age %>
<%= @game.min_players %>
<%= @game.max_players %>
<%= @game.time %>
<%= @game.content %>

<%= link_to 'EDIT', edit_game_path(@game) %>

<%= link_to 'DELETE', game_path(@game), method: :delete, data: { confirm: "Are you sure?" }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>